### PR TITLE
add add_worker api

### PR DESCRIPTION
**Pull request by longlene**

### CODE REVIEW

**Comment by silviucpp** [comment]
@longlene can you please add also a test case for this function ?

**Comment by silviucpp** [comment]
Also please notice that calling that method concurrently will lead to unexpected behavior.

**Comment by longlene** [comment]
Maybe it's OK for concurrent usage:
For example, if two processes call the add_worker at the same time, they get the same size and then try to start worker in supervisor, one will failed for {error, already_started} and size will increase only when start worker successfully.
Please correct me if I missed something.

**Comment by silviucpp** [comment]
@longlene you are right ! I will merge this

**Pull request merged**
